server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /urdf/ {
        alias /usr/share/nginx/html/urdf/;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=86400";
        types {
            application/xml urdf;
            application/octet-stream stl;
            model/stl stl;
        }
    }
}
