physical_ai_server:
  ros__parameters:
    omx_f:
      observation_list:
        - camera
        - state

      camera_topic_list:
        - camera:/camera/camera/color/image_rect_raw/compressed

      joint_topic_list:
        - follower:/joint_states
        - leader:/leader/joint_trajectory

      joint_list:
        - leader

      joint_order:
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - gripper_joint_1
